version: "3.2"

services:
  laravel:
    build: ../
    entrypoint: ""
    #env_file: ../.env
    env_file: https://mychallenge4bucket.s3.ap-southeast-2.amazonaws.com/.env
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
     - 80:80
